In [1]:
a = 10
print(a)

10


In [3]:
#to check given number is even or odd using if else

num = int(input("Enter a number: "))
if num % 2 == 0:
    print("Even")
else:
    print("Odd")

Even


In [5]:
#to check given number is positive or negative function


def check(num):
    if num > 0:
        print("Positive")
    elif num < 0:
        print("Negative")
    else:
        print("Zero")


check(19)

Positive


In [7]:
#printing first natural numbers using for loop

n = int(input("Enter a number: "))
for i in range(1, n+1):
    print(i, end=" ")

1 2 3 4 5 6 7 8 9 10 

In [11]:
#printing first natural numbers using for loop and break statement

n = int(input("Enter a number: "))
for i in range(1, n+1):
    print(i, end=" ")
    if i == 5:
        break   #break statement is used to terminate the loop  when i is equal to 5    
    

1 2 3 4 5 

In [23]:
#printing using while loop

n = int(input("Enter a number: "))

i = 1

while i <= n :
    print(i,end=" ")
    i+=1


1 2 3 4 5 6 7 8 9 

In [24]:
#checking eligibility for voting

age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible for voting")
else:
    print("You are not eligible for voting")

You are not eligible for voting


In [27]:
#checking eligibility for voting using function 

def check_voting(age):
    if age >= 18:
        print("You are eligible for voting")
    else:
        print("You are not eligible for voting")

check_voting(20)



You are eligible for voting


In [28]:
#even or odd using function

def check_even_odd(num):
    if num % 2 == 0:
        print("Even")
    else:
        print("Odd")
check_even_odd(10)


Even


In [29]:
#roundoff
import math

n =float(input("Enter a number: "))

print(math.ceil(n))
print(math.floor(n))
print(round(n))


3
2
2


In [32]:
#square,square root,cube,cube root

import math 

n = int(input("Enter a number: "))
print(math.sqrt(n))
print(math.pow(n,2))
print(math.pow(n,3))
print(math.pow(n,1/3))


2.23606797749979
25.0
125.0
1.7099759466766968


In [33]:
#multiplication table

n = int(input("Enter a number: "))
for i in range (1,11):
    print(n,"*",i,"=",n*i)
    

10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100


In [34]:
import numpy as np

a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [35]:
#printing 2d arrays

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
